***Feature Encoding***    
Feature encoding is the process of transforming categorical features into numeric features. This is necessary because machine learning algorithms can only handle numeric features. There are many different ways to encode categorical features, and each method has its own advantages and disadvantages. In this notebook, we will explore some of the most popular methods for encoding categorical features, such as:

* Label encoding
* Ordinal encoding
* One-hot encoding
* Binary encoding

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# data load
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [12]:
df['encoded_time'].value_counts()

encoded_time
0    176
1     68
Name: count, dtype: int64

In [6]:
# let's encode the time in labelencoder with sklearn
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
le = LabelEncoder()
df['encoded_time'] = le.fit_transform(df['time'])
df.head()

   total_bill   tip     sex smoker  day    time  size  encoded_time
0       16.99  1.01  Female     No  Sun  Dinner     2             0
1       10.34  1.66    Male     No  Sun  Dinner     3             0
2       21.01  3.50    Male     No  Sun  Dinner     3             0
3       23.68  3.31    Male     No  Sun  Dinner     2             0
4       24.59  3.61  Female     No  Sun  Dinner     4             0

In [7]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [13]:
df['encoded_day'].value_counts()

encoded_day
2.0    87
3.0    76
0.0    62
1.0    19
Name: count, dtype: int64

In [10]:
# ordinal encoding the day column using specific order
oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
df['encoded_day'] = oe.fit_transform(df[['day']])
df.head()

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
0,16.99,1.01,Female,No,Sun,Dinner,2,0,3.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0,3.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0,3.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0,3.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,3.0

In [11]:
# one hot encoding on day column
ohe = OneHotEncoder()
ohe.fit_transform(df[['sex']]).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [14]:
# example of one hot encoding
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
# example of one hot encoding
titanic = sns.load_dataset('titanic')

onehot_encoder = OneHotEncoder(sparse=False)
embarked_onehot = onehot_encoder.fit_transform(titanic[['embarked']])
embarked_onehot_df = pd.DataFrame(embarked_onehot, columns=onehot_encoder.get_feature_names_out(['embarked']))
titanic = pd.concat([titanic.reset_index(drop=True), embarked_onehot_df.reset_index(drop=True)], axis=1)
titanic.head()

c:\Users\Arman\anaconda3\envs\phython_ml\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,0.0,1.0,0.0

In [19]:
 !pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from category_encoders) (1.26.2)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from category_encoders) (1.3.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from category_encoders) (1.11.4)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.1-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: pandas>=1.0.5 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from category_encoders) (2.1.4)
Collecting patsy>=0.5.1 (from category_encoders)
  Downloading patsy-0.5.4-py2.py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arman\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\arman\appdata\roaming\python\python311\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\arman\anaconda3\envs\phython_ml\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\arman\appdata\roaming\python\python311\site-packages (from statsmodels>=0.9.0->category_encoders) (23.2)
Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
   ---------------------------------------- 0.0/81.9 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/81.9 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/81.9 kB ? eta -:--:--
   --------------- ------------------------ 30.7/81.9 kB 187.9 kB/s eta 0:00:01
   --------------- ------------------------ 30.7/81.9 kB 187.9 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 151.3 kB/s eta 0:00:01
   ------------------------------ --------- 61.4/81.9 kB 204.8 kB/s eta 0:00:01
   ----------------------------------- ---- 71.7/81.9 kB 206.9 kB/s eta 0:00:01
   ---------------------------------------- 81.9/81.9 kB 208.2 kB/s eta 0:00:00
Downloading patsy-0.5.4-py2.py3-none-any.whl (233 kB)
   ---------------------------------------- 0.0/233.9 kB ? eta -:--:--
   --------------- ------------------------ 92.2/233.9 kB 2.6 MB/s eta 0:00:01
   ------------------- -------------------- 112.6/233.9 kB 2.2 MB/s eta 0:00:01
   ------------------- -------------------- 112.6/233.9 kB 2.2 MB/s eta 0:00:01
   --------------------- ---------------- 133.1/233.9 kB 714.4 kB/s eta 0:00:01
   ------------------------------- ------ 194.6/233.9 kB 841.6 kB/s eta 0:00:01
   ------------------------------------ - 225.3/233.9 kB 811.5 kB/s eta 0:00:01
   -------------------------------------- 233.9/233.9 kB 716.8 kB/s eta 0:00:00
Downloading statsmodels-0.14.1-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.9/9.9 MB 1.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.9 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.1/9.9 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.1/9.9 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.1/9.9 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.1/9.9 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.1/9.9 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.1/9.9 MB 939.5 kB/s eta 0:00:10
   ---- ----------------------------------- 1.2/9.9 MB 957.6 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.9 MB 1.0 MB/s eta 0:00:09
   ----- ---------------------------------- 1.4/9.9 MB 1.0 MB/s eta 0:00:09
   ----- ---------------------------------- 1.4/9.9 MB 1.0 MB/s eta 0:00:09
   ------ --------------------------------- 1.5/9.9 MB 1.0 MB/s eta 0:00:09
   ------ --------------------------------- 1.5/9.9 MB 1.0 MB/s eta 0:00:09
   ------ --------------------------------- 1.7/9.9 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.7/9.9 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.7/9.9 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.7/9.9 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.7/9.9 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.7/9.9 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.0/9.9 MB 1.1 MB/s eta 0:00:07
   -------- ------------------------------- 2.0/9.9 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.9 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.9 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.9 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.9 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.9 MB 1.1 MB/s eta 0:00:08
   --------- ------------------------------ 2.3/9.9 MB 1.1 MB/s eta 0:00:07
   --------- ------------------------------ 2.3/9.9 MB 1.1 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.9 MB 1.1 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.9 MB 1.1 MB/s eta 0:00:08
   --------- ------------------------------ 2.4/9.9 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.5/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.5/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.5/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.7/9.9 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.7/9.9 MB 1.0 MB/s eta 0:00:08
   ----------- ---------------------------- 2.7/9.9 MB 1.0 MB/s eta 0:00:08
   ----------- ---------------------------- 2.8/9.9 MB 990.1 kB/s eta 0:00:08
   ----------- ---------------------------- 2.8/9.9 MB 990.1 kB/s eta 0:00:08
   ----------- ---------------------------- 2.8/9.9 MB 986.6 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.9 MB 984.8 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.9 MB 981.3 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.9 MB 976.2 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.9 MB 976.2 kB/s eta 0:00:08
   ------------ --------------------------- 3.0/9.9 MB 958.1 kB/s eta 0:00:08
   ------------ --------------------------- 3.0/9.9 MB 960.1 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.9 MB 960.4 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.9 MB 959.1 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.9 MB 954.7 kB/s eta 0:00:08
   ------------ --------------------------- 3.2/9.9 MB 952.3 kB/s eta 0:00:07
   ------------- -------------------------- 3.2/9.9 MB 951.2 kB/s eta 0:00:07
   ------------- -------------------------- 3.3/9.9 MB 954.6 kB/s eta 0:00:07
   ------------- -------------------------- 3.3/9.9 MB 949.0 kB/s eta 0:00:07
   ------------- -------------------------- 3.3/9.9 MB 946.5 kB/s eta 0:00:07
   ------------- -------------------------- 3.4/9.9 MB 948.4 kB/s eta 0:00:07
   ------------- -------------------------- 3.4/9.9 MB 946.3 kB/s eta 0:00:07
   -------------- ------------------------- 3.5/9.9 MB 946.4 kB/s eta 0:00:07
   -------------- ------------------------- 3.5/9.9 MB 938.9 kB/s eta 0:00:07
   -------------- ------------------------- 3.5/9.9 MB 939.3 kB/s eta 0:00:07
   -------------- ------------------------- 3.6/9.9 MB 941.2 kB/s eta 0:00:07
   -------------- ------------------------- 3.6/9.9 MB 943.0 kB/s eta 0:00:07
   -------------- ------------------------- 3.6/9.9 MB 941.8 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.9 MB 936.1 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.9 MB 935.3 kB/s eta 0:00:07
   --------------- ------------------------ 3.8/9.9 MB 937.1 kB/s eta 0:00:07
   --------------- ------------------------ 3.8/9.9 MB 939.1 kB/s eta 0:00:07
   --------------- ------------------------ 3.9/9.9 MB 933.4 kB/s eta 0:00:07
   --------------- ------------------------ 3.9/9.9 MB 932.7 kB/s eta 0:00:07
   ---------------- ----------------------- 4.0/9.9 MB 934.4 kB/s eta 0:00:07
   ---------------- ----------------------- 4.0/9.9 MB 933.7 kB/s eta 0:00:07
   ---------------- ----------------------- 4.0/9.9 MB 929.8 kB/s eta 0:00:07
   ---------------- ----------------------- 4.1/9.9 MB 929.2 kB/s eta 0:00:07
   ---------------- ----------------------- 4.1/9.9 MB 930.9 kB/s eta 0:00:07
   ---------------- ----------------------- 4.2/9.9 MB 932.6 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.9 MB 933.8 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.9 MB 926.8 kB/s eta 0:00:07
   ----------------- ---------------------- 4.3/9.9 MB 929.5 kB/s eta 0:00:06
   ----------------- ---------------------- 4.3/9.9 MB 930.1 kB/s eta 0:00:06
   ----------------- ---------------------- 4.4/9.9 MB 927.5 kB/s eta 0:00:06
   ----------------- ---------------------- 4.4/9.9 MB 924.8 kB/s eta 0:00:06
   ------------------ --------------------- 4.4/9.9 MB 927.2 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.9 MB 928.0 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.9 MB 928.4 kB/s eta 0:00:06
   ------------------ --------------------- 4.6/9.9 MB 925.8 kB/s eta 0:00:06
   ------------------ --------------------- 4.6/9.9 MB 926.4 kB/s eta 0:00:06
   ------------------ --------------------- 4.7/9.9 MB 923.9 kB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.9 MB 925.6 kB/s eta 0:00:06
   ------------------- -------------------- 4.8/9.9 MB 927.1 kB/s eta 0:00:06
   ------------------- -------------------- 4.8/9.9 MB 924.6 kB/s eta 0:00:06
   ------------------- -------------------- 4.8/9.9 MB 923.3 kB/s eta 0:00:06
   ------------------- -------------------- 4.9/9.9 MB 925.6 kB/s eta 0:00:06
   -------------------- ------------------- 4.9/9.9 MB 927.1 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.9 MB 922.1 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.9 MB 922.3 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.9 MB 923.9 kB/s eta 0:00:06
   -------------------- ------------------- 5.1/9.9 MB 925.3 kB/s eta 0:00:06
   -------------------- ------------------- 5.1/9.9 MB 924.9 kB/s eta 0:00:06
   -------------------- ------------------- 5.2/9.9 MB 922.6 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.9 MB 924.0 kB/s eta 0:00:06
   --------------------- ------------------ 5.3/9.9 MB 921.7 kB/s eta 0:00:05
   --------------------- ------------------ 5.3/9.9 MB 923.1 kB/s eta 0:00:05
   --------------------- ------------------ 5.3/9.9 MB 923.5 kB/s eta 0:00:05
   --------------------- ------------------ 5.4/9.9 MB 922.4 kB/s eta 0:00:05
   ---------------------- ----------------- 5.4/9.9 MB 921.3 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 921.6 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 924.7 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 919.1 kB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 920.5 kB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 921.8 kB/s eta 0:00:05
   ----------------------- ---------------- 5.7/9.9 MB 923.0 kB/s eta 0:00:05
   ----------------------- ---------------- 5.7/9.9 MB 921.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 920.8 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 919.7 kB/s eta 0:00:05
   ----------------------- ---------------- 5.9/9.9 MB 921.0 kB/s eta 0:00:05
   ----------------------- ---------------- 5.9/9.9 MB 921.3 kB/s eta 0:00:05
   ------------------------ --------------- 5.9/9.9 MB 920.4 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.9 MB 918.4 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.9 MB 918.1 kB/s eta 0:00:05
   ------------------------ --------------- 6.1/9.9 MB 919.3 kB/s eta 0:00:05
   ------------------------ --------------- 6.1/9.9 MB 917.5 kB/s eta 0:00:05
   ------------------------ --------------- 6.2/9.9 MB 918.7 kB/s eta 0:00:05
   ------------------------- -------------- 6.2/9.9 MB 919.0 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 918.0 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 919.8 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 918.0 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 917.7 kB/s eta 0:00:04
   ------------------------- -------------- 6.4/9.9 MB 916.9 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 918.0 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 918.9 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 910.2 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 911.4 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 912.7 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 912.9 kB/s eta 0:00:04
   --------------------------- ------------ 6.7/9.9 MB 914.0 kB/s eta 0:00:04
   --------------------------- ------------ 6.7/9.9 MB 910.5 kB/s eta 0:00:04
   --------------------------- ------------ 6.7/9.9 MB 908.9 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 907.3 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 909.0 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 906.8 kB/s eta 0:00:04
   --------------------------- ------------ 6.9/9.9 MB 908.1 kB/s eta 0:00:04
   ---------------------------- ----------- 6.9/9.9 MB 908.3 kB/s eta 0:00:04
   ---------------------------- ----------- 7.0/9.9 MB 908.1 kB/s eta 0:00:04
   ---------------------------- ----------- 7.0/9.9 MB 907.9 kB/s eta 0:00:04
   ---------------------------- ----------- 7.0/9.9 MB 907.7 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.9 MB 907.5 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.9 MB 907.3 kB/s eta 0:00:04
   ----------------------------- ---------- 7.2/9.9 MB 908.4 kB/s eta 0:00:03
   ----------------------------- ---------- 7.2/9.9 MB 907.7 kB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 907.9 kB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 909.0 kB/s eta 0:00:03
   ----------------------------- ---------- 7.4/9.9 MB 907.1 kB/s eta 0:00:03
   ----------------------------- ---------- 7.4/9.9 MB 907.4 kB/s eta 0:00:03
   ------------------------------ --------- 7.4/9.9 MB 907.6 kB/s eta 0:00:03
   ------------------------------ --------- 7.5/9.9 MB 907.0 kB/s eta 0:00:03
   ------------------------------ --------- 7.5/9.9 MB 908.0 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 907.4 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 905.2 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 903.8 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.9 MB 902.5 kB/s eta 0:00:03
   ------------------------------- -------- 7.7/9.9 MB 904.7 kB/s eta 0:00:03
   ------------------------------- -------- 7.7/9.9 MB 904.6 kB/s eta 0:00:03
   ------------------------------- -------- 7.8/9.9 MB 904.9 kB/s eta 0:00:03
   ------------------------------- -------- 7.8/9.9 MB 904.2 kB/s eta 0:00:03
   ------------------------------- -------- 7.9/9.9 MB 904.0 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.9 MB 905.0 kB/s eta 0:00:03
   -------------------------------- ------- 8.0/9.9 MB 904.8 kB/s eta 0:00:03
   -------------------------------- ------- 8.0/9.9 MB 904.8 kB/s eta 0:00:03
   -------------------------------- ------- 8.0/9.9 MB 904.6 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 905.6 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 905.9 kB/s eta 0:00:02
   --------------------------------- ------ 8.2/9.9 MB 905.2 kB/s eta 0:00:02
   --------------------------------- ------ 8.2/9.9 MB 906.2 kB/s eta 0:00:02
   --------------------------------- ------ 8.3/9.9 MB 907.1 kB/s eta 0:00:02
   --------------------------------- ------ 8.3/9.9 MB 908.0 kB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 906.8 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 906.7 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 906.5 kB/s eta 0:00:02
   ---------------------------------- ----- 8.5/9.9 MB 907.4 kB/s eta 0:00:02
   ---------------------------------- ----- 8.5/9.9 MB 908.3 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 909.2 kB/s eta 0:00:02
   ----------------------------------- ---- 8.6/9.9 MB 909.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 908.8 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 909.8 kB/s eta 0:00:02
   ----------------------------------- ---- 8.8/9.9 MB 910.7 kB/s eta 0:00:02
   ----------------------------------- ---- 8.8/9.9 MB 909.4 kB/s eta 0:00:02
   ----------------------------------- ---- 8.8/9.9 MB 909.3 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 909.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 908.9 kB/s eta 0:00:02
   ------------------------------------ --- 9.0/9.9 MB 909.8 kB/s eta 0:00:01

In [17]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
from category_encoders import BinaryEncoder

binary_encoder = BinaryEncoder()
df_binary = binary_encoder.fit_transform(df['day'])

In [21]:
# use pandas for feature encoding

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
# use pandas get dummies
get_dummies = pd.get_dummies(df, columns=['day'])
get_dummies.head()

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,False,False,False,True
1,10.34,1.66,Male,No,Dinner,3,False,False,False,True
2,21.01,3.50,Male,No,Dinner,3,False,False,False,True
3,23.68,3.31,Male,No,Dinner,2,False,False,False,True
4,24.59,3.61,Female,No,Dinner,4,False,False,False,True